#theme = "hugo-future-imperfect-master"
baseURL = "https://cbf.netlify.com/"
languageCode = "en-us"
title = "carl b frederick"
preserveTaxonomyNames = true
paginate = 3
googleAnalytics = ""
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  # Sets the meta tag description
  description          = "This is a space where I will blog about R, education and perhaps some intermittent posts about homebrewing."
  # Sets the navbarTitle that appears in the top left of the navigation bar
  navbarTitle          = "Carl B Frederick"
  # Sets where "View More Posts" links
  viewMorePostLink     = "/post/"

# Optional Params
  # Sets navbarTitle to match the section of the website
  dynamicTitles        = true
  # Sets RSS icons to appear on the sidebar with the social media buttons
  rssAppearAtTop       = true
  rssAppearAtBottom    = true
  # Sets Social Media icons to appear on the sidebar
  socialAppearAtTop    = true
  socialAppearAtBottom = true
  # Sets Categories to sort by number of posts instead of alphabetical
  categoriesByCount    = true
  # Sets Estimated Reading Time to appear in post headers
  includeReadingTime   = true
  
  # Sets Social Share links to appear on posts
  socialShare          = true

  # These are optional params related to the sidebar. They are recommended, but not
  # required for proper functionality. HTML is supported within the params.
[params.intro]
  header    = ""

  paragraph = "A digital space where I discuss R, education and perhaps the occasional homebrewing topic."

  about     = "Carl is a sociologist turned education researcher in Wisconsin who takes a bit too much joy in the minutiae of statistical programming."

  # This appears at the top of the sidebar above params.intro.header.
  # A width of less than 100px is recommended from a design perspective.
  [params.intro.pic]
    src       = "/img/main/logo_small.jpg"
    # Sets Image to be a cirlce
    circle    = false
    # Sets Image to be Future Imperfect's hexagon
    imperfect = true
    width     = ""
    alt       = "carl headshot"
    
[params.postAmount]
# Sets the number of recent posts to show in the sidebar. The default value is 5.
    sidebar = 5

# Sets the menu items in the navigation bar
# Identifier prepends a Font Awesome icon to the menu item
[[menu.main]]
  name = "Home"
  url = "/"
  identifier = "fa fa-home"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  identifier = "fa fa-id-card-o"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/post/"
  identifier = "fa fa-newspaper-o"
  weight = 3

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  identifier = "fa fa-sitemap"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  identifier = "fa fa-envelope-o"
  weight = 5
  
# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted. These are the icons affected by socialAppearAtTop
# and socialAppearAtBottom.
[social]
  # Coding Communities
  github           = "carlbfrederick"
  gitlab           = ""
  stackoverflow    = "5216535" # User Number
  bitbucket        = ""
  jsfiddle         = ""
  codepen          = ""
  # Publishing Communities
  medium           = ""
  # Professional/Business Oriented Communities
  slideshare       = ""
  # Social Networks
  facebook         = "carlbfrederick"
  googleplus       = ""
  reddit           = "carlbfrederick"
  quora            = ""
  youtube          = ""
  vimeo            = ""
  whatsapp         = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat         = ""
    qq             = "" # User ID Number
  instagram        = "carlbfrederick"
  tumblr           = ""
  twitter          = "carlbfrederick"
  skype            = ""
  snapchat         = ""
  pinterest        = ""
  telegram         = ""
  vine             = ""
  googlescholar    = "UXkwv5UAAAAJ"
  orcid            = ""
  researchgate     = ""    
  # Email
  email            = ""


